# docker-compose.yml

version: '3.8'

services:
  # Nginx Web Server
  nginx:
    image: nginx:1.25-alpine
    container_name: numista_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - numista-network

  # PHP Application (Laravel)
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
      args:
        UID: ${UID:-1000}
    container_name: numista_app
    environment:
      # Pass the Stripe secrets to be available for the supervisor process and the application.
      STRIPE_SECRET: ${STRIPE_SECRET}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET} # THE FIX: Add this line
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    networks:
      - numista-network

  # PostgreSQL Database
  db:
    image: postgres:16-alpine
    container_name: numista_db
    restart: unless-stopped
    ports:
      - "54320:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE:-numista}
      POSTGRES_USER: ${DB_USERNAME:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    volumes:
      - numista-db-data:/var/lib/postgresql/data
    networks:
      - numista-network
  
  # Mailpit Email Catcher
  mailpit:
    image: 'axllent/mailpit:latest'
    container_name: numista_mailpit
    ports:
      - "1025:1025" # SMTP Port
      - "8025:8025" # Web UI Port
    networks:
      - numista-network

networks:
  numista-network:
    driver: bridge

volumes:
  numista-db-data:
    driver: local