# docker-compose.yml

version: '3.8'

services:
  # Nginx Web Server
  nginx:
    image: nginx:1.25-alpine
    container_name: numista_nginx
    ports:
      - "8080:80" # Access the app via http://localhost:8080
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - numista-network

  # PHP Application (Laravel)
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
      args:
        UID: ${UID:-1000} # Pass the host user's UID
    container_name: numista_app
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    networks:
      - numista-network

  # PostgreSQL Database
  db:
    image: postgres:16-alpine
    container_name: numista_db
    restart: unless-stopped
    ports:
      - "54320:5432" # Access the DB from host via port 54320 if needed
    environment:
      POSTGRES_DB: ${DB_DATABASE:-numista}
      POSTGRES_USER: ${DB_USERNAME:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    volumes:
      - numista-db-data:/var/lib/postgresql/data
    networks:
      - numista-network

networks:
  numista-network:
    driver: bridge

volumes:
  numista-db-data:
    driver: local