<?php

namespace Numista\Collection\UI\Filament\Resources\ItemResource\RelationManagers;

use Filament\Forms\Form;
use Filament\Resources\RelationManagers\RelationManager;
use Filament\Tables\Actions\AttachAction;
use Filament\Tables\Actions\BulkActionGroup;
use Filament\Tables\Actions\DetachAction;
use Filament\Tables\Actions\DetachBulkAction;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Model; // <-- Import the Model class

class CategoriesRelationManager extends RelationManager
{
    // Defines the Eloquent relationship method name on the Item model.
    protected static string $relationship = 'categories';

    /**
     * Set a custom, translatable title for the relation manager section.
     * This overrides the default title generated by Filament.
     */
    public static function getTitle(Model $ownerRecord, string $pageClass): string
    {
        return __('panel.label_categories'); // Using our existing translation key for "Categorías"
    }

    // We don't need a form here because we are not creating/editing categories,
    // only attaching existing ones. The AttachAction provides its own modal form.
    public function form(Form $form): Form
    {
        return $form->schema([]);
    }

    public function table(Table $table): Table
    {
        return $table
            ->recordTitleAttribute('name')
            ->columns([
                TextColumn::make('name')
                    ->label(__('panel.field_name')),
            ])
            ->filters([
                // No filters needed for this simple table.
            ])
            ->headerActions([
                AttachAction::make()
                    ->label(__('panel.action_attach'))
                    ->modalHeading(__('panel.modal_attach_title_category'))
                    ->modalSubmitActionLabel(__('panel.modal_attach_button'))
                    ->preloadRecordSelect(),
            ])
            ->actions([
                DetachAction::make()
                    ->label(__('panel.action_detach')),
            ])
            ->bulkActions([
                BulkActionGroup::make([
                    DetachBulkAction::make(),
                ]),
            ]);
    }
}
