name: Laravel CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:
    name: Run Laravel Tests
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Set up PHP with extensions
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: pdo, pdo_pgsql, pdo_sqlite, zip, intl, gd
        
    # 3. Copy the .env file for testing
    - name: Copy .env file
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    # 4. Install Composer dependencies
    - name: Install Composer dependencies
      run: composer install --no-progress --prefer-dist --optimize-autoloader

    # 5. Generate application key
    - name: Generate app key
      run: php artisan key:generate

    # 6. Run database migrations (on the in-memory SQLite DB)
    - name: Run migrations
      run: php artisan migrate

    # 7. Run Pest tests
    - name: Execute tests (Pest)
      run: php artisan test